INSERT INTO breed (name, fci_id) VALUES
	('SRD',                                000), 
	('Border Collie',                      297), 
	('Continental Toy Spaniel Papillon',   077), 
	('Continental Toy Spaniel Phalène',    077), 
	('Belgian Shepherd Dog Groenendael',   015), 
	('Belgian Shepherd Dog Laekenois',     015), 
	('Belgian Shepherd Dog Malinois',      015), 
	('Belgian Shepherd Dog Tervueren',     015), 
	('Mudi',                               238),
	('Portuguese Water Dog',               037), 
	('Affenpinscher',                      186),
	('Afghan Hound',                       228),
	('Atlas Mountain Dog',                 247),
	('Airedale Terrier',                   007),
	('Akita',                              255),
	('Alaskan Malamute',                   243),
	('Alpine Dachsbracke',                 254),
	('American Akita',                     344),
	('American Cocker Spaniel Black',      167),
	('American Cocker Spaniel Solid',      167),
	('American Cocker Spaniel Particolor', 167),
	('American Foxhound',                  303),
	('American Staffordshire Terrier',     286),
	('American Water Spaniel',             301),
	('Medium-Sized Anglo-French Hound',    325),
	('Kintamani-Bali Dog',                 362),
	('Appenzeller Mountain Dog',           046),
	('Ariege Hound',                       020),
	('Australian Cattle Dog',              287),
	('Australian Kelpie',                  293),
	('Australian Shepherd',                342),
	('Silky Terrier',                      236),
	('Australian Stumpy Tail Cattle Dog',  351),
	('Australian Terrier',                 008),
	('Azawakh',                            307), 
	('Barbet',                             105),
	('Basenji',                            043),
	('Beagle',                             161),
	('Beagle-Harrier',                     290),
	('Boston Terrier',                     140),
	('Boxer Fawn',                         144),
	('Boxer Brindle',                      144),
	('German Shorthaired Pointer',         119),
	('Miniature Bull Terrier',             359),
	('Cane Corso',                         343),
	('Poodle Standard',                    172),
	('Poodle Medium',                      172),
	('Poodle Miniature',                   172),
	('Poodle Toy',                         172),
	('Catalan Sheepdog Longhaired',        087),
	('Catalan Sheepdog Smoothhaired',      087),
	('English Cocker Spaniel Solid',       005),
	('English Cocker Spaniel Particolour', 005),
	('English Cocker Spaniel Tricolour',   005),
	('English Cocker Spaniel Roan',        005),
	('Doberman Pinscher',                  143),
	('Flat-Coated Retriever',              121),
	('Golden Retriever',                   111),
	('Jack Russell Terrier',               345),
	('Rhodesian Ridgeback',                146),
	('Parson Russell Terrier',             339),
	('Pyrenean Sheepdog, Smooth-faced',    138),
	('Pyrenean Sheepdog, Longhaired',      141),
	('Portuguese Pointer',                 187),
	('Miniature Pinscher',                 185),
	('Portuguese Podengo Grande',          094),
	('Portuguese Podengo Medio',           094),
	('Portuguese Podengo Pequeno',         094),
	('Pug',                                253),
	('Labrador Retriever',                 122),
	('Rottweiler',                         147),
	('Miniature Schnauzer',                183),
	('Giant Schnauzer',                    181),
	('Standard Schnauzer',                 182),
	('Shetland Sheepdog',                  088),
	('German Miniature Spitz',             097),
	('Teckel',                             148),
	('Weimaraner',                         099),
	('Yorkshire Terrier',                  086);

INSERT INTO category (name, min_height, max_height) VALUES
	('Small',   0, 35),
	('Medium', 35, 43),
	('Large',  43,  0);

INSERT INTO level (name) VALUES
	('Pre-Agility'), -- club dependent level
	('Grau 0'), 
	('Grau 1'), -- FCI Level 1
	('Grau 2'), -- FCI Level 2
	('Grau 3'), -- FCI Level 3
	('Veteranos'),
	('Infantis'); -- this is weird, as this level is dependent on the handler's age, not the dog's

	