INSERT INTO person (name, is_judge) VALUES 
	('Alexandra Gomes', 0),
	('Alexandra Rodrigues', 0),
	('Ana Emauz', 0),
	('Ana Faria', 1),
	('Ana Paula Jorge', 0),
	('Ana Silva', 0),
	('Andreia Duarte', 0),
	('Angela Pereira', 0),
	('Beatriz Rodrigues', 0),
	('Belmiro', 0),
	('Bruno Branco', 0),
	('Carla Almeida', 0),
	('Carlos Telo', 0),
	('Dulce Sameiro', 0),
	('Elisabete Mendes', 0),
	('Francisco Esteves', 0),
	('Hugo Alves', 0),
	('Hugo Santos', 0),
	('Ines Figueiredo', 0),
	('Isabel Guedes', 0),
	('Isabel Serrão', 0),
	('João Carlos Oliveira', 0),
	('João Fernandes', 0),
	('Júlio Rodrigues', 0),
	('Leonor Reis', 0),
	('Lúcia Marcos', 0),
	('Luís Santos', 0),
	('Luísa Oliveira', 0),
	('Madalena Correia', 0),
	('Mariana Fino', 0),
	('Mariana Ribeiro', 0),
	('Mário Araújo', 0),
	('Marta Martins', 0),
	('Marta Maya Brandão', 0),
	('Matilde Chora', 0),
	('Melissa Costa', 0),
	('Miguel Freire', 0),
	('Paulo Cristão', 0),
	('Paulo Mateus', 0),
	('Paulo Sousa', 0),
	('Rafael', 0),
	('Ricardo Silva', 0),
	('Rita Nunes', 0),
	('Rita Santos', 0),
	('Rui Abreu', 0),
	('Sandra Cordeiro', 0),
	('Sandra Silva', 0),
	('Sérgio de Sousa', 1),
	('Sofia Alves', 0),
	('Susana Roncon Chaves', 0),
	('Tânia Fernandes', 0),
	('Teresa Leitão', 0),
	('Uriel Oliveira', 0),
	('Vitor Ribeiro', 0),
	('Volodymyr Nikulin', 0),
	('Wendy Oliver Beavis', 0),
	('Pánczél Gyöngyi', 0),
	('Tomás Narciso', 0),
	('João Narciso', 0),
	('Sofia Narciso', 0),
	('Vasco Ribeiro', 0),
	('Hugo Simões', 0),
	('Carla Cruz', 0),
	('João Fernandes', 0),
	('Gonçalo Amorim', 0) ;

INSERT INTO dog (name, reg_name, date_of_birth, height, chip_id, breed_id) VALUES
	('Choco', '', '', 0, '', 0),
	('Elfie', '', '', 0, '', 0),
	('Kurt', '', '', 0, '', 0),
	('Finn', '', '', 0, '', 0),
	('Yasmine', '', '', 0, '', 0),
	('Simão', '', '', 0, '', 0),
	('Tobias', '', '', 0, '', 0),
	('Fox', '', '', 0, '', 0),
	('Sweet', 'SweetSingingIrisMalone', '', 0, '', 0),
	('Be', '', '', 0, '', 0),
	('Shuva', '', '', 0, '', 0),
	('Luna', '', '', 0, '', 0),
	('Nocas', '', '', 0, '', 0),
	('Bela', '', '', 0, '', 0),
	('SHEILA', '', '', 0, '', 0),
	('Freddy', '', '', 0, '', 0),
	('Noa', '', '', 0, '', 0),
	('Lupi', '', '', 0, '', 0),
	('Nyugi', '', '', 0, '', 0),
	('Twix', '', '', 0, '', 0),
	('Shakira', '', '', 0, '', 0),
	('Ishka', '', '', 0, '', 0),
	('Shep', '', '', 0, '', 0),
	('Mel', '', '', 0, '', 0),
	('Belota', '', '', 0, '', 0),
	('Luna', 'Shake da Pedra da Anixa', '', 0, '', 0),
	('Flicka', '', '', 0, '', 0),
	('Amelie', '', '', 0, '', 0),
	('Letty', '', '', 0, '', 0),
	('King', '', '', 0, '', 0),
	('Skye', 'Skye - II', '', 0, '', 0),
	('Maggie', 'Maggie-II', '', 0, '', 0),
	('Estrela', '', '', 0, '', 0),
	('Foxy', '', '', 0, '', 0),
	('Bruna', '', '', 0, '', 0),
	('Sonic', '', '', 0, '', 0),
	('Yuuki', 'Yuuki Bushido Courage', '', 0, '', 0),
	('Mia', '', '', 0, '', 0),
	('Ghallie', '', '', 0, '', 0),
	('Tofu', '', '', 0, '', 0),
	('RAFA', '', '', 0, '', 0),
	('Zor', '', '', 0, '', 0),
	('NAVY', '', '', 0, '', 0),
	('Pingo', '', '', 0, '', 0),
	('Lyra', '', '', 0, '', 0),
	('Alex', '', '', 0, '', 0),
	('Thor', '', '', 0, '', 0),
	('Bacco', '', '', 0, '', 0),
	('Sookie', 'Astrid Finne Nejaknyt Empire', '', 0, '', 0),
	('Flash', '', '', 0, '', 0),
	('Kaya', '', '', 0, '', 0),
	('Giló', '', '', 0, '', 0),
	('Turbo Toby', '', '', 0, '', 0),
	('Cat', '', '', 0, '', 0),
	('KIRA', '', '', 0, '', 0),
	('Goa', '', '', 0, '', 0),
	('Shorty', '', '', 0, '', 0),
	('Zoe', 'Zoe II', '', 0, '', 0),
	('Dili', '', '', 0, '', 0),
	('Holly', '', '', 0, '', 0),
	('Pipa', '', '', 0, '', 0),
	('Bacho', '', '', 0, '', 0),
	('Zoom', '', '', 0, '', 0),
	('Kylo', '', '', 0, '', 0),
	('Sheepy', '', '', 0, '', 0),
	('Smash', '', '', 0, '', 0),
	('Salina', '', '', 0, '', 0),
	('Ozzy', '', '', 0, '', 0),
	('Elsa', '', '', 0, '', 0),
	('Kuka', '', '', 0, '', 0),
	('Bu', '', '', 0, '', 0),
	('Zip', '', '', 0, '', 0);
